// <auto-generated />
namespace SleepinManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class time_of_creation_invoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(time_of_creation_invoice));
        
        string IMigrationMetadata.Id
        {
            get { return "202311211641214_time_of_creation_invoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
