// <auto-generated />
namespace SleepinManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class moved_extra_beds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moved_extra_beds));
        
        string IMigrationMetadata.Id
        {
            get { return "202311211318442_moved_extra_beds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
